image: barichello/godot-ci:3.4.2

cache:
  key: import-assets
  paths:
    - .import/

    
variables:
    EXPORT_NAME: checkers
    
stages:
  - export
  - deploy
  

web:
  stage: export
  script:
    - mkdir -v -p build/web
    - godot -v --path ./project --export "HTML5" ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

pages:
  stage: deploy
  dependencies:
    - web
  script:
    - rm -rf public
    - cp -r build/web public
  artifacts:
    paths:
      - public