image: barichello/godot-ci:3.4.2

cache:
  key: import-assets
  paths:
    - .import/

    
variables:
    EXPORT_NAME: checkers
    
stages:
  - export
  - deploy
 
linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot -v --path ./project --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --path ./project --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  script:
    - mkdir -v -p build/mac
    - godot -v --path ./project --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac
      
web:
  stage: export
  script:
    - mkdir -v -p build/web
    - godot -v --path ./project --export "HTML5" ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

pages:
  stage: deploy
  dependencies:
    - web
  script:
    # This ensures the `pages` branch is available.
    - git fetch
    - git checkout pages
    - rm -f *.md
    - mv build/web/** ./public
  artifacts:
    paths:
      - public