name: "godot-ci export"

env:
    GODOT_VERSION: 3.4.2
    EXPORT_NAME: checkers
    
on:
    workflow_dispatch:
    push:
        branches:
          - main
        
jobs:
    export-windows:
        name: Windows Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                lfs: true
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Windows Build
            run: |
                mkdir -v -p build/windows
                godot -v --path ./project --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: checkers-windows
                path: build/windows
         
    export-linux:
        name: Linux Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                lfs: true
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Linux Build
            run: |
                mkdir -v -p build/linux
                godot -v --path ./project --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: checkers-linux
                path: build/linux
                
    export-mac:
        name: Mac Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                lfs: true
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Mac Build
            run: |
                mkdir -v -p build/mac
                godot -v --path ./project --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: checkers-mac
                path: build/mac
                
    export-web:
        name: Web Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                lfs: true
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Web Build
            run: |
                mkdir -v -p build/web
                godot -v --path ./project --export "HTML5" ../build/web/$EXPORT_NAME.html
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: checkers-web
                path: build/web
                
          - name: Compress Project
            run |
                cd build/web
                wget https://raw.githubusercontent.com/nodeca/pako/master/dist/pako_inflate.min.js
                gzip -f checkers.wasm
                gzip -f checkers.pck
                FIND="<script type='text/javascript' src='checkers.js'></script>"
                REPLACE="<script type=\"text/javascript\" src=\"pako_inflate.min.js\"></script>$FIND"
                sed -i -e "s@$FIND@$REPLACE@" checkers.html
                FIND="function loadXHR(resolve, reject, file, tracker) {"
                REPLACE=$FIND" if (file.substr(-5) === '.wasm' || file.substr(-4) === '.pck') { file += '.gz'; var resolve_orig = resolve; resolve = function(xhr) { return resolve_orig(xhr.responseURL.substr(-3) === '.gz' ? { response: pako.inflate(xhr.response), responseType: xhr.responseType, responseURL: xhr.responseURL, status: xhr.status, statusText: xhr.statusText } : xhr); }; }"
                sed -i -e "s@$FIND@$REPLACE@" checkers.js
                
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/web
                force_orphan: true
                user_name: 'github-ci[bot]'
                user_email: 'github-actions[bot]@users.noreply.github.com'
                commit_message: 'Publish to gh-pages'