name: "godot-ci export"

env:
    GODOT_VERSION: 3.4.2
    EXPORT_NAME: checkers
    
on:
    workflow_dispatch:
    push:
        branches:
          - main
        
jobs:
    export-windows:
        name: Windows Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Windows Build
            run: |
                mkdir -v -p build/windows
                godot -v --path ./project --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: $EXPORT_NAME-windows
                path: build/windows
         
    export-linux:
        name: Linux Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Linux Build
            run: |
                mkdir -v -p build/linux
                godot -v --path ./project --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: $EXPORT_NAME-linux
                path: build/linux
                
    export-mac:
        name: Mac Export
        runs-on: ubuntu-20.04
        
        container:
            image: barichello/godot-ci:3.4.2
            
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            
          - name: Setup
            run: |
                mkdir -v -p ~/.local/share/godot/templates
                mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          - name: Mac Build
            run: |
                mkdir -v -p build/mac
                godot -v --path ./project --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v1
            with:
                name: $EXPORT_NAME-mac
                path: build/linux